apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "spark-history-server.fullname" . }}-auth
  namespace: {{ .Release.Namespace }} 
  labels:
      {{- include "spark-history-server.labels" $ | trim | nindent 4 }}

stringData:
{{- range $key, $val := .Values.passwordPairs }}
  {{ $key }}: "{{ $val }}"
{{- end }}

  

