apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-history-server.fullname" . }}
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "spark-history-server.labels" $ | trim | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations: 
          {{- with .Values.service.annotations }}
              {{- toYaml . | nindent 4 }}
          {{- end }}
  {{- end }}

spec:
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end}}
  ports:
    - name: http
      port: 18080
      protocol: TCP
      targetPort: 18080
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ required "Node Port number for Spark History is required" .Values.service.nodePortSparkHistoryPort }}
      {{- end }}
  selector:
    name: {{ include "spark-history-server.fullname" . }}
  type: {{ required "Service type is required" .Values.service.type }}
  