apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jupyterlab.fullname" . }}
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "jupyterlab.labels" $ | trim | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ include "jupyterlab.fullname" . }}
  replicas: 1
  strategy:
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
  template:
    metadata:
      labels:
        name: {{ include "jupyterlab.fullname" . }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.image.pullSecrets | indent 8 }}
      {{- end }}   
      serviceAccountName: "{{ include "jupyterlab.fullname" . }}-sa"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
              allowPrivilegeEscalation: false
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8888         
          command: ["bash", "start-notebook.sh"]   
          args:
            - "--NotebookApp.token="
            {{if not ( eq (index .Values.ingress.http.paths 0 "pathType") "Prefix")}}
            - "--NotebookApp.base_url=jupyterlab"
            {{end}}
            - "--KernelSpecManager.ensure_native_kernel=False"
            - "--NotebookApp.notebook_dir=/home/jovyan/work"
  
          readinessProbe:
            initialDelaySeconds: 90
            tcpSocket:
              port: 8888

          volumeMounts:
            - name: sparkmagic
              mountPath: /tmp/sparkmagic.json
              subPath: sparkmagic
            - name: secret
              mountPath: /tmp/quickstart.ipynb
              subPath: quickstart
            - name: secret
              mountPath: /home/jovyan/.jupyter/jupyter_notebook_config.py
              subPath: jupyter_notebook_config
            - name: custom-file
              mountPath: /tmp/requirements.txt
              subPath: requirements.txt
            - name: custom-file
              mountPath: /usr/local/bin/start-notebook.sh
              subPath: start-notebook.sh
            - name: persist-notebooks
              mountPath: /home/jovyan/work

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: sparkmagic
          configMap:
            name: {{ include "jupyterlab.fullname" . }}-sparkmagic
        - name: secret
          secret:
            secretName: {{ include "jupyterlab.fullname" . }}-secret
        - name: custom-file
          configMap:
            name: {{ template "jupyterlab.fullname" . }}-custom-file
        - name: persist-notebooks
          persistentVolumeClaim:
              claimName: {{ include "jupyterlab.fullname" . }}-persist-notebooks
      
