apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jupyterlab.fullname" . }}-persist-notebooks
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "jupyterlab.labels" $ | trim | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"