apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyterlab.fullname" . }}
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "jupyterlab.labels" $ | trim | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations: 
          {{- with .Values.service.annotations }}
              {{- toYaml . | nindent 4 }}
          {{- end }}
  {{- end }}
spec:
    {{- if .Values.service.clusterIP }}
    clusterIP: {{ .Values.service.clusterIP }}
    {{- end}}
    ports:
        -   name: http
            port: 8888
            protocol: TCP
            {{- if eq .Values.service.type "NodePort" }}
            nodePort: {{ required "Node Port number for jupyterlab is required" .Values.service.nodePortJupyterlabPort }}
            {{- end }}
    selector:
        name: {{ include "jupyterlab.fullname" . }}
    type: {{ required "Service type is required" .Values.service.type }}


