apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jupyterlab.fullname" . }}-sa
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "jupyterlab.labels" $ | trim | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "jupyterlab.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jupyterlab.labels" $ | trim | nindent 4 }}
rules:
- apiGroups: [ "" ]
  resources: [ "pods", "services", "configmaps", "pods/log" ]
  verbs: [ "*" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "jupyterlab.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jupyterlab.labels" $ | trim | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "jupyterlab.fullname" . }}-sa
roleRef:
  kind: Role
  name: {{ include "jupyterlab.fullname" . }}
  apiGroup: rbac.authorization.k8s.io




