apiVersion: v1
kind: Service
metadata:
  name: {{ include "lighter.fullname" . }}
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "lighter.labels" $ | trim | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations: 
          {{- with .Values.service.annotations }}
              {{- toYaml . | nindent 4 }}
          {{- end }}
  {{- end }}
spec:
    {{- if .Values.service.clusterIP }}
    clusterIP: {{ .Values.service.clusterIP }}
    {{- end}}
    ports:
        -   name: api
            port: 8080
            protocol: TCP
            {{- if eq .Values.service.type "NodePort" }}
            nodePort: {{ required "Node Port number for Spark UI is required" .Values.service.nodePortLighterPort }}
            {{- end }}
        -   name: javagw
            port: 25333
            protocol: TCP
    selector:
        name: {{ include "lighter.fullname" . }}
    type: {{ required "Service type is required" .Values.service.type }}