apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lighter.fullname" . }}-sa
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "lighter.labels" $ | trim | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "lighter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lighter.labels" $ | trim | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "pods/log", "persistentvolumeclaims"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "lighter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lighter.labels" $ | trim | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "lighter.fullname" . }}-sa
roleRef:
  kind: Role
  name: {{ include "lighter.fullname" . }}
  apiGroup: rbac.authorization.k8s.io