# Default values for jupyterlab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  repository: jupyter/minimal-notebook
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "python-3.11.6"
  # pullSecrets:
  # - name: myRegistryKeySecretName

nameOverride: ""
fullnameOverride: ""


service:
  # Options are ClusterIP (if use Ingress), NodePort, LoadBalancer
  type: ClusterIP
  # optional no need value
  clusterIP:
  # Only need to fill up if service type is NodePort
  nodePortLighterPort: 33001
  annotations: {}
    # networking.gke.io/load-balancer-type: "Internal"
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true"

ingress:
  enabled: true
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

    # acme.cert-manager.io/http01-edit-in-place: "true"
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    # cert-manager.io/issue-temporary-certificate: "true"
    # kubernetes.io/ingress.class: nginx

  # leave empty if do not have dns name
  host:
  http:
    paths:
    - backend:
        service:
          name: "{{ include \"jupyterlab.fullname\" . }}"
          port:
            number: 8888
      path: /jupyterlab
      pathType: ImplementationSpecific
  tls: []
    # - hosts:
    #    - spark-thrift-server.begonia.aisingapore.net
    #   secretName: chart-example-tls

resources:
  limits: {}
  requests:
    cpu: 0.25
    memory: 512Mi

# Jupyter password is generated using below python code
# from notebook.auth import passwd
# passwd("spark ecosystem")
jupyterPassword: argon2:$argon2id$v=19$m=10240,t=10,p=8$rqX1GcIVDKwH73enY4FDXQ$WUxU8yQaMaIdp3CO14FGns74LzrxCGmqa3WwkZBe7jE
# refer to lighter values.yaml on how to generate this password
lighterPassword: 5Wmi95w4

# Only need to fill in if install on isolated namespace
lighter:
  # only need this value if install jupyter subchart standalone
  namespace: helmall
