apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark-thrift-server.fullname" . }}-google-secret
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "spark-thrift-server.labels" $ | trim | nindent 4 }}
stringData:
  google_sa.json: |
    {
        
    }