apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark-thrift-server.fullname" . }}-secret
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "spark-thrift-server.labels" $ | trim | nindent 4 }}
stringData:
  hive-site.xml: |
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?><!--
      Licensed to the Apache Software Foundation (ASF) under one or more
      contributor license agreements.  See the NOTICE file distributed with
      this work for additional information regarding copyright ownership.
      The ASF licenses this file to You under the Apache License, Version 2.0
      (the "License"); you may not use this file except in compliance with
      the License.  You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
    --><configuration>

    {{- if .Values.s3a.secretKey }}
    <property>
      <name>fs.s3a.access.key</name>
      <value>{{ required "S3A key required" .Values.s3a.accessKey }}</value>
    </property>
    <property>
      <name>fs.s3a.secret.key</name>
      <value>{{ required "S3A secret required" .Values.s3a.secretKey }}</value>
    </property>
    <property>
      <name>fs.s3a.endpoint</name>
      <value>{{ required "S3A endpoint required" .Values.s3a.endpoint }}</value>
    </property>
    {{- end -}}

    <property>
    <name>fs.s3a.path.style.access</name>
    <value>true</value>
    </property>

    <property>
      <name>hive.input.format</name>
      <value>io.delta.hive.HiveInputFormat</value>
    </property>
    <property>
      <name>hive.tez.input.format</name>
      <value>io.delta.hive.HiveInputFormat</value>
    </property>

    <property>
      <name>fs.gs.auth.service.account.json.keyfile</name>
      <value>/opt/spark/google_sa.json</value>
    </property>
    
    <property>
      <name>fs.gs.working.dir</name>
      <value>/</value>
    </property>
    <property>
      <name>fs.gs.path.encoding</name>
      <value>uri-path</value>
    </property>
    <property>
      <name>fs.gs.reported.permissions</name>
      <value>777</value>
    </property>

    </configuration>

  hiveserver2-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <!--
      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License. See accompanying LICENSE file.
    -->

    <!-- Put site-specific property overrides in this file. -->
    <configuration>
    <!-- <property>
      <name>hive.security.authorization.manager</name>
      <value>org.apache.hadoop.hive.ql.security.authorization.plugin.sqlstd.SQLStdHiveAuthorizerFactory</value>
    </property>
    <property>
      <name>hive.security.authorization.enabled</name>
      <value>true</value>
    </property>
    <property>
      <name>hive.security.authenticator.manager</name>
      <value>org.apache.hadoop.hive.ql.security.SessionStateUserAuthenticator</value>
    </property>
    <property>
      <name>hive.metastore.uris</name>
      <value></value>
    </property> -->
    </configuration>


