apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-thrift-server.fullname" . }}
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "spark-thrift-server.labels" $ | trim | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations: 
          {{- with .Values.service.annotations }}
              {{- toYaml . | nindent 4 }}
          {{- end }}
  {{- end }}

spec:
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end}}
  ports:
  # disabled this 
  # - name: spark-ui
  #   port: 4040
  #   protocol: TCP
  #   targetPort: 4040
  #   {{- if or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer") }}
  #   nodePort: {{ required "Node Port number for Spark UI is required" .Values.service.nodePortSparkUIPort }}
  #   {{- end }}

  - name: spark-thrift
    port: 10000
    protocol: TCP
    targetPort: 10000
    {{- if or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer") }}
    nodePort: {{ required "Node Port number for Spark UI is required" .Values.service.nodePortSparkThriftServerPort }}
    {{- end }}
  selector:
    name: {{ include "spark-thrift-server.fullname" . }}
  type: {{ required "Service type is required" .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-thrift-server.fullname" . }}-headless
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "spark-thrift-server.labels" $ | trim | nindent 4 }}
spec: 
  clusterIP: None # spark workers use this service to communciate with the driver
  selector:
    name: {{ include "spark-thrift-server.fullname" . }}



