name: Test Schema Support for Kubernetes Versions

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            include:
              - kubernetes_version: 1.23.0
              - kubernetes_version: 1.29.0
    steps:
      - uses: actions/checkout@v2
      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            kubeconform
            kustomize
          kubeconform: '0.6.4'
          kustomize: '5.3.0'
          helm: '3.14.3'
      - run: |
          set -o pipefail
          cd kcustomize/example/prod
          helm template testing ../../../installer --post-renderer ./kustomize.sh --values ./values.yaml | kubeconform -kubernetes-version=${{ matrix.kubernetes_version }} -verbose
          